#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)"

: "${WLT_OUT_DIR:=/tmp/winlator-core-upscale-$(date +%Y%m%d_%H%M%S)}"
: "${WLT_SCENARIO_MATRIX:=freewine11:1}"
: "${WLT_BASELINE_LABEL:=freewine11}"
: "${WLT_ARTIFACT_KEYS:=freewine11}"
: "${WLT_RUN_SEED:=0}"
: "${WLT_RUN_ARTIFACT_REFRESH:=0}"
: "${WLT_CAPTURE_NETWORK_DIAG:=0}"
: "${WLT_CAPTURE_RUNTIME_CONTENTS:=1}"
: "${WLT_CAPTURE_PREFS:=1}"
: "${WLT_CAPTURE_UI:=1}"
: "${WLT_FAIL_ON_SEVERITY_AT_OR_ABOVE:=medium}"
: "${WLT_FAIL_ON_CONFLICT_SEVERITY_AT_OR_ABOVE:=medium}"

printf '[forensic-core-upscale] scenarios=%s baseline=%s\n' "${WLT_SCENARIO_MATRIX}" "${WLT_BASELINE_LABEL}"

ADB_SERIAL="${ADB_SERIAL:-}" \
WLT_OUT_DIR="${WLT_OUT_DIR}" \
WLT_SCENARIO_MATRIX="${WLT_SCENARIO_MATRIX}" \
WLT_BASELINE_LABEL="${WLT_BASELINE_LABEL}" \
WLT_ARTIFACT_KEYS="${WLT_ARTIFACT_KEYS}" \
WLT_RUN_SEED="${WLT_RUN_SEED}" \
WLT_RUN_ARTIFACT_REFRESH="${WLT_RUN_ARTIFACT_REFRESH}" \
WLT_CAPTURE_NETWORK_DIAG="${WLT_CAPTURE_NETWORK_DIAG}" \
WLT_CAPTURE_RUNTIME_CONTENTS="${WLT_CAPTURE_RUNTIME_CONTENTS}" \
WLT_CAPTURE_PREFS="${WLT_CAPTURE_PREFS}" \
WLT_CAPTURE_UI="${WLT_CAPTURE_UI}" \
WLT_FAIL_ON_SEVERITY_AT_OR_ABOVE="${WLT_FAIL_ON_SEVERITY_AT_OR_ABOVE}" \
WLT_FAIL_ON_CONFLICT_SEVERITY_AT_OR_ABOVE="${WLT_FAIL_ON_CONFLICT_SEVERITY_AT_OR_ABOVE}" \
  bash "${ROOT_DIR}/ci/winlator/forensic-adb-harvard-suite.sh"
