package com.winlator.cmod.container

import com.winlator.cmod.box86_64.Box86_64Preset
import com.winlator.cmod.core.DefaultVersion
import com.winlator.cmod.core.WineInfo
import com.winlator.cmod.core.WineThemeManager
import com.winlator.cmod.fexcore.FEXCorePreset

/**
 * Donor-compatible container settings snapshot used by staged transfer lanes.
 *
 * Ae.solator does not yet drive a Compose editor around this model, so this
 * version keeps the data surface and safe map conversion helpers without
 * pulling in Compose saveable dependencies before the first honest compile.
 */
data class ContainerData(
    val name: String = "",
    val screenSize: String = Container.DEFAULT_SCREEN_SIZE,
    val envVars: String = Container.DEFAULT_ENV_VARS,
    val graphicsDriver: String = Container.DEFAULT_GRAPHICS_DRIVER,
    val graphicsDriverVersion: String = "",
    val graphicsDriverConfig: String = "",
    var dxwrapper: String = Container.DEFAULT_DXWRAPPER,
    val dxwrapperConfig: String = "",
    val audioDriver: String = Container.DEFAULT_AUDIO_DRIVER,
    val wincomponents: String = Container.DEFAULT_WINCOMPONENTS,
    val drives: String = Container.DEFAULT_DRIVES,
    val execArgs: String = "",
    val executablePath: String = "",
    val installPath: String = "",
    val showFPS: Boolean = false,
    val launchRealSteam: Boolean = false,
    val allowSteamUpdates: Boolean = false,
    val steamType: String = "normal",
    val cpuList: String = Container.getFallbackCPUList(),
    val cpuListWoW64: String = Container.getFallbackCPUListWoW64(),
    val wow64Mode: Boolean = true,
    val startupSelection: Byte = Container.STARTUP_SELECTION_ESSENTIAL,
    val box86Version: String = DefaultVersion.BOX64,
    val box64Version: String = DefaultVersion.BOX64,
    val box86Preset: String = Box86_64Preset.COMPATIBILITY,
    val box64Preset: String = Box86_64Preset.COMPATIBILITY,
    val desktopTheme: String = WineThemeManager.DEFAULT_DESKTOP_THEME,
    val containerVariant: String = Container.DEFAULT_VARIANT,
    val wineVersion: String = WineInfo.MAIN_WINE_VERSION.identifier(),
    val emulator: String = Container.DEFAULT_EMULATOR,
    val fexcoreVersion: String = DefaultVersion.FEXCORE,
    val fexcoreTSOMode: String = "Fast",
    val fexcoreX87Mode: String = "Fast",
    val fexcoreMultiBlock: String = "Disabled",
    val fexcorePreset: String = FEXCorePreset.INTERMEDIATE,
    val renderer: String = "gl",
    val csmt: Boolean = true,
    val videoPciDeviceID: Int = 1728,
    val offScreenRenderingMode: String = "fbo",
    val strictShaderMath: Boolean = true,
    val useDRI3: Boolean = true,
    val videoMemorySize: String = "2048",
    val mouseWarpOverride: String = "disable",
    val shaderBackend: String = "glsl",
    val useGLSL: String = "enabled",
    val sdlControllerAPI: Boolean = true,
    val useSteamInput: Boolean = false,
    val enableXInput: Boolean = true,
    val enableDInput: Boolean = true,
    val dinputMapperType: Byte = 1,
    val disableMouseInput: Boolean = false,
    val touchscreenMode: Boolean = false,
    val shooterMode: Boolean = true,
    val gestureConfig: String = "",
    val externalDisplayMode: String = "off",
    val externalDisplaySwap: Boolean = false,
    val language: String = "english",
    val forceDlc: Boolean = false,
    val steamOfflineMode: Boolean = false,
    val useLegacyDRM: Boolean = false,
    val unpackFiles: Boolean = false,
    val suspendPolicy: String = "manual",
    val portraitMode: Boolean = false,
    val sharpnessEffect: String = "None",
    val sharpnessLevel: Int = 100,
    val sharpnessDenoise: Int = 100,
) {
    fun toMap(): Map<String, Any?> = mapOf(
        "name" to name,
        "screenSize" to screenSize,
        "envVars" to envVars,
        "graphicsDriver" to graphicsDriver,
        "graphicsDriverVersion" to graphicsDriverVersion,
        "graphicsDriverConfig" to graphicsDriverConfig,
        "dxwrapper" to dxwrapper,
        "dxwrapperConfig" to dxwrapperConfig,
        "audioDriver" to audioDriver,
        "wincomponents" to wincomponents,
        "drives" to drives,
        "execArgs" to execArgs,
        "executablePath" to executablePath,
        "installPath" to installPath,
        "showFPS" to showFPS,
        "launchRealSteam" to launchRealSteam,
        "allowSteamUpdates" to allowSteamUpdates,
        "steamType" to steamType,
        "cpuList" to cpuList,
        "cpuListWoW64" to cpuListWoW64,
        "wow64Mode" to wow64Mode,
        "startupSelection" to startupSelection.toInt(),
        "box86Version" to box86Version,
        "box64Version" to box64Version,
        "box86Preset" to box86Preset,
        "box64Preset" to box64Preset,
        "desktopTheme" to desktopTheme,
        "containerVariant" to containerVariant,
        "wineVersion" to wineVersion,
        "emulator" to emulator,
        "fexcoreVersion" to fexcoreVersion,
        "fexcoreTSOMode" to fexcoreTSOMode,
        "fexcoreX87Mode" to fexcoreX87Mode,
        "fexcoreMultiBlock" to fexcoreMultiBlock,
        "fexcorePreset" to fexcorePreset,
        "renderer" to renderer,
        "csmt" to csmt,
        "videoPciDeviceID" to videoPciDeviceID,
        "offScreenRenderingMode" to offScreenRenderingMode,
        "strictShaderMath" to strictShaderMath,
        "useDRI3" to useDRI3,
        "videoMemorySize" to videoMemorySize,
        "mouseWarpOverride" to mouseWarpOverride,
        "shaderBackend" to shaderBackend,
        "useGLSL" to useGLSL,
        "sdlControllerAPI" to sdlControllerAPI,
        "useSteamInput" to useSteamInput,
        "enableXInput" to enableXInput,
        "enableDInput" to enableDInput,
        "dinputMapperType" to dinputMapperType.toInt(),
        "disableMouseInput" to disableMouseInput,
        "touchscreenMode" to touchscreenMode,
        "shooterMode" to shooterMode,
        "gestureConfig" to gestureConfig,
        "externalDisplayMode" to externalDisplayMode,
        "externalDisplaySwap" to externalDisplaySwap,
        "language" to language,
        "forceDlc" to forceDlc,
        "steamOfflineMode" to steamOfflineMode,
        "useLegacyDRM" to useLegacyDRM,
        "unpackFiles" to unpackFiles,
        "suspendPolicy" to suspendPolicy,
        "portraitMode" to portraitMode,
        "sharpnessEffect" to sharpnessEffect,
        "sharpnessLevel" to sharpnessLevel,
        "sharpnessDenoise" to sharpnessDenoise,
    )

    companion object {
        @JvmStatic
        fun fromMap(savedMap: Map<String, Any?>): ContainerData = ContainerData(
            name = savedMap.stringValue("name", ""),
            screenSize = savedMap.stringValue("screenSize", Container.DEFAULT_SCREEN_SIZE),
            envVars = savedMap.stringValue("envVars", Container.DEFAULT_ENV_VARS),
            graphicsDriver = savedMap.stringValue("graphicsDriver", Container.DEFAULT_GRAPHICS_DRIVER),
            graphicsDriverVersion = savedMap.stringValue("graphicsDriverVersion", ""),
            graphicsDriverConfig = savedMap.stringValue("graphicsDriverConfig", ""),
            dxwrapper = savedMap.stringValue("dxwrapper", Container.DEFAULT_DXWRAPPER),
            dxwrapperConfig = savedMap.stringValue("dxwrapperConfig", ""),
            audioDriver = savedMap.stringValue("audioDriver", Container.DEFAULT_AUDIO_DRIVER),
            wincomponents = savedMap.stringValue("wincomponents", Container.DEFAULT_WINCOMPONENTS),
            drives = savedMap.stringValue("drives", Container.DEFAULT_DRIVES),
            execArgs = savedMap.stringValue("execArgs", ""),
            executablePath = savedMap.stringValue("executablePath", ""),
            installPath = savedMap.stringValue("installPath", ""),
            showFPS = savedMap.booleanValue("showFPS", false),
            launchRealSteam = savedMap.booleanValue("launchRealSteam", false),
            allowSteamUpdates = savedMap.booleanValue("allowSteamUpdates", false),
            steamType = savedMap.stringValue("steamType", "normal"),
            cpuList = savedMap.stringValue("cpuList", Container.getFallbackCPUList()),
            cpuListWoW64 = savedMap.stringValue("cpuListWoW64", Container.getFallbackCPUListWoW64()),
            wow64Mode = savedMap.booleanValue("wow64Mode", true),
            startupSelection = savedMap.byteValue("startupSelection", Container.STARTUP_SELECTION_ESSENTIAL),
            box86Version = savedMap.stringValue("box86Version", DefaultVersion.BOX64),
            box64Version = savedMap.stringValue("box64Version", DefaultVersion.BOX64),
            box86Preset = savedMap.stringValue("box86Preset", Box86_64Preset.COMPATIBILITY),
            box64Preset = savedMap.stringValue("box64Preset", Box86_64Preset.COMPATIBILITY),
            desktopTheme = savedMap.stringValue("desktopTheme", WineThemeManager.DEFAULT_DESKTOP_THEME),
            containerVariant = savedMap.stringValue("containerVariant", Container.DEFAULT_VARIANT),
            wineVersion = savedMap.stringValue("wineVersion", WineInfo.MAIN_WINE_VERSION.identifier()),
            emulator = savedMap.stringValue("emulator", Container.DEFAULT_EMULATOR),
            fexcoreVersion = savedMap.stringValue("fexcoreVersion", DefaultVersion.FEXCORE),
            fexcoreTSOMode = savedMap.stringValue("fexcoreTSOMode", "Fast"),
            fexcoreX87Mode = savedMap.stringValue("fexcoreX87Mode", "Fast"),
            fexcoreMultiBlock = savedMap.stringValue("fexcoreMultiBlock", "Disabled"),
            fexcorePreset = savedMap.stringValue("fexcorePreset", FEXCorePreset.INTERMEDIATE),
            renderer = savedMap.stringValue("renderer", "gl"),
            csmt = savedMap.booleanValue("csmt", true),
            videoPciDeviceID = savedMap.intValue("videoPciDeviceID", 1728),
            offScreenRenderingMode = savedMap.stringValue("offScreenRenderingMode", "fbo"),
            strictShaderMath = savedMap.booleanValue("strictShaderMath", true),
            useDRI3 = savedMap.booleanValue("useDRI3", true),
            videoMemorySize = savedMap.stringValue("videoMemorySize", "2048"),
            mouseWarpOverride = savedMap.stringValue("mouseWarpOverride", "disable"),
            shaderBackend = savedMap.stringValue("shaderBackend", "glsl"),
            useGLSL = savedMap.stringValue("useGLSL", "enabled"),
            sdlControllerAPI = savedMap.booleanValue("sdlControllerAPI", true),
            useSteamInput = savedMap.booleanValue("useSteamInput", false),
            enableXInput = savedMap.booleanValue("enableXInput", true),
            enableDInput = savedMap.booleanValue("enableDInput", true),
            dinputMapperType = savedMap.byteValue("dinputMapperType", 1),
            disableMouseInput = savedMap.booleanValue("disableMouseInput", false),
            touchscreenMode = savedMap.booleanValue("touchscreenMode", false),
            shooterMode = savedMap.booleanValue("shooterMode", true),
            gestureConfig = savedMap.stringValue("gestureConfig", ""),
            externalDisplayMode = savedMap.stringValue("externalDisplayMode", "off"),
            externalDisplaySwap = savedMap.booleanValue("externalDisplaySwap", false),
            language = savedMap.stringValue("language", "english"),
            forceDlc = savedMap.booleanValue("forceDlc", false),
            steamOfflineMode = savedMap.booleanValue("steamOfflineMode", false),
            useLegacyDRM = savedMap.booleanValue("useLegacyDRM", false),
            unpackFiles = savedMap.booleanValue("unpackFiles", false),
            suspendPolicy = savedMap.stringValue("suspendPolicy", "manual"),
            portraitMode = savedMap.booleanValue("portraitMode", false),
            sharpnessEffect = savedMap.stringValue("sharpnessEffect", "None"),
            sharpnessLevel = savedMap.intValue("sharpnessLevel", 100),
            sharpnessDenoise = savedMap.intValue("sharpnessDenoise", 100),
        )

        private fun Map<String, Any?>.stringValue(key: String, fallback: String): String =
            this[key] as? String ?: fallback

        private fun Map<String, Any?>.booleanValue(key: String, fallback: Boolean): Boolean =
            this[key] as? Boolean ?: fallback

        private fun Map<String, Any?>.intValue(key: String, fallback: Int): Int =
            (this[key] as? Number)?.toInt() ?: fallback

        private fun Map<String, Any?>.byteValue(key: String, fallback: Byte): Byte =
            (this[key] as? Number)?.toByte() ?: fallback
    }
}
